### ISSUE TITLE
MediaRenamer: Add automatic move after rename

### ISSUE THREAD

**Issue by ozthe2** [joer89/Media#12]
A nice feature would be to auto move the renamed files for example to:
/media/tv/{series name}/season {number}

I

**Comment by joer89** [comment]
That would be very cool, i think we should put it within a switch (-folderStructure) say.

**Comment by ozthe2** [comment]
We need to know the root path eg d:\media\tv

So probably a param like: PathToTVMedia or similar.  If that path is present then after the rename we do the logic for moving the renamed files to the correct location.

**Comment by joer89** [comment]
I like the sound of that.
