### ISSUE TITLE
PlexFormat

### ISSUE THREAD

**Issue by joer89** [joer89/Media#16]
Hello

I have added in the auto move and it only moves when a rename has occurred. 

There is problem with plexformat param on some Regex.

Pattern1 & 2 uses this format Title SseasonNumberEepisodeNumber so when we use plexformat param we duplicate on S and E for season and episode.

We need plexFormat param on Pattern3 to put it in the plex format.

but apart from that, from the words of the Lego Movie "Everything is Awesome" :).

**Comment by joer89** [comment]
I have fixed the plex formatting issue with a if statement under the plexformatting param.

**Comment by joer89** [comment]
I haven't tested this thoroughly but The Simpsons.S01E02.720.RIP doesn't seem to be working now.

i believe this is our only issue though :).

**Comment by ozthe2** [comment]
This is because there is a space between "The" and "Simpsons"

**Comment by joer89** [comment]
Oh OK sounds good, ill create some more Regex, does this mean we don't need -replace "[\._]"," "?
