### ISSUE TITLE
Re: Media renamer

### ISSUE THREAD

**Issue by ozthe2** [joer89/Media#9]
I think there is an issue when you run the script and the files are renamed, but then run the script for a second time on the same set of files in the same location.  I will confirm later but I thought I saw it result in correctly named files become renamed to something else entirely!

@joer89

**Comment by joer89** [comment]
Oh interesting, it should just log saying no match found??

**Comment by joer89** [comment]
I'm stumped! i don't get why its renaming wrong, its renaming to C S01xE01? what was changed do you know?

**Comment by ozthe2** [comment]
It shouldn't be too bad to figure out - I'll take a look during the week.

**Comment by joer89** [comment]
I've been having a look, ok cool, I'll tell you if I figure it out. Also it
very made the move parameters :)

**Comment by ozthe2** [comment]
What do you mean "It very made the move parameters"

**Comment by joer89** [comment]
I made the move parameter, auto spelling screwed up :).
